<?php

return [
    'defaults' => [
        'global' => [
            'browser_engine' => env('INSTAGRAM_BROWSER_ENGINE', 'chrome'),
            'cloak_humanize_enabled' => env('INSTAGRAM_CLOAK_HUMANIZE', false),
            'cloak_human_preset' => env('INSTAGRAM_CLOAK_HUMAN_PRESET', ''),
            'process_stall_timeout_seconds' => 900,
            'node_watchdog_timeout_seconds' => 900,
            'script_watchdog_enabled' => true,
            'browser_disconnect_abort' => true,
            'navigation_timeout_seconds' => 120,
            'post_login_wait_ms' => 2500,
            'typing_delay_ms' => 35,
            'profile_switch_extra_attempts' => 2,
            'live_preview_enabled' => true,
            'skip_debug_artifacts' => false,
            'block_heavy_resources' => false,
        ],
        'mini' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 2,
            'session_fallback_enabled' => true,
        ],
        'profile' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 2,
            'visible_count_attempts' => 3,
        ],
        'lists' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 3,
            'max_items' => 0,
            'max_scroll_rounds' => 100000,
            'partition_large_lists' => true,
            'partition_threshold' => 250,
            'search_queries_per_dialog' => 8,
            'search_partition_max_items' => 250,
            'search_max_depth' => 3,
            'progress_checkpoint_size' => 250,
            'search_target_max_items' => 0,
            'search_target_max_scroll_rounds' => 60,
            'search_input_max_attempts' => 3,
            'search_wait_ms' => 900,
        ],
        'posts' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 3,
            'max_items' => 100,
            'max_scroll_rounds' => 40,
            'max_likes_per_post' => 250,
            'max_comments_per_post' => 250,
            'open_likes_dialog_enabled' => true,
            'like_dialog_max_scroll_rounds' => 40,
            'comment_dialog_max_scroll_rounds' => 40,
        ],
        'suggestions' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 3,
            'max_items' => 500,
            'inline_max_rounds' => 60,
            'dialog_max_rounds' => 100,
        ],
        'suggestion_deep_search' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 3,
            'candidate_max_items' => 300,
            'candidate_error_attempts' => 1,
            'candidate_retry_delay_seconds' => 3,
            'candidate_inline_max_rounds' => 40,
            'candidate_dialog_max_rounds' => 70,
            'public_list_max_scroll_rounds' => 60,
            'skip_previously_checked' => true,
            'no_match_skip_after' => 2,
            'max_scraper_profile_switches' => 3,
            'profile_hover_cards_enabled' => true,
            'profile_hover_card_wait_ms' => 850,
        ],
        'public_connections' => [
            'error_attempts' => 1,
            'retry_delay_seconds' => 5,
            'resume_previous' => true,
            'skip_completed_candidates' => true,
            'candidate_max_attempts' => 3,
            'candidate_retry_delay_seconds' => 6,
            'candidate_retry_max_delay_seconds' => 30,
            'candidate_max_duration_seconds' => 1200,
            'dialog_missing_max_attempts' => 2,
            'rate_limit_account_switch_enabled' => true,
            'max_scraper_profile_switches' => 3,
        ],
    ],
];
